### ISSUE TITLE
This is not compatible with the latest Cypress code `12.2.0`

### ISSUE THREAD

**Issue by rakeshnambiar** [dev-tools-ai/devtoolsai_demo_cypress#2]
The error that I am getting while executing the tests on the latest version. Whereas if I switch back to version `10.11.0` everything is working as expected.

```
 (Attempt 1 of 2) An uncaught error was detected outside of a test
  1) An uncaught error was detected outside of a test

  0 passing (356ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     CypressError: The following error originated from your test code, not from Cypress.

  > Cannot overwite the `find` query. Queries cannot be overwritten.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

https://on.cypress.io/api
      at ./node_modules/@devtools-ai/cypress-sdk/dist/cypress/support/commands.js (webpack:///./node_modules/@devtools-ai/cypress-sdk/dist/cypress/support/commands.js:337:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./node_modules/@devtools-ai/cypress-sdk/dist/index.js (webpack:///./node_modules/@devtools-ai/cypress-sdk/dist/index.js:4:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:18:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at 0 (http://localhost:61972/__cypress/tests?p=cypress/support/e2e.js:13726:18)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at eval (webpack:///webpack/bootstrap:83:0)
      at eval (http://localhost:61972/__cypress/tests?p=cypress/support/e2e.js:87:10)
  
  From Cypress Internals:
        at internalError (http://localhost:61972/__cypress/runner/cypress_runner.js:153171:99)
        at Object.overwrite (http://localhost:61972/__cypress/runner/cypress_runner.js:153251:11)
        at <unknown> (http://localhost:61972/__cypress/runner/cypress_runner.js:161610:23)
        at tryCatcher (http://localhost:61972/__cypress/runner/cypress_runner.js:11327:23)
        at Object.gotValue (http://localhost:61972/__cypress/runner/cypress_runner.js:10469:18)
        at Object.gotAccum (http://localhost:61972/__cypress/runner/cypress_runner.js:10458:25)
        at Object.tryCatcher (http://localhost:61972/__cypress/runner/cypress_runner.js:11327:23)
        at Promise._settlePromiseFromHandler (http://localhost:61972/__cypress/runner/cypress_runner.js:9262:31)
        at Promise._settlePromise (http://localhost:61972/__cypress/runner/cypress_runner.js:9319:18)
        at Promise._settlePromiseCtx (http://localhost:61972/__cypress/runner/cypress_runner.js:9356:10)
        at _drainQueueStep (http://localhost:61972/__cypress/runner/cypress_runner.js:6038:12)
        at _drainQueue (http://localhost:61972/__cypress/runner/cypress_runner.js:6027:9)
        at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:61972/__cypress/runner/cypress_runner.js:6043:5)
        at Async.drainQueues (http://localhost:61972/__cypress/runner/cypress_runner.js:5913:14)
```

**Comment by rakeshnambiar** [comment]
@etienne-dev-tools Please could you help?

**Comment by rakeshnambiar** [comment]
Thanks for fixing it

**Comment by rakeshnambiar** [comment]
I am still having issues with the latest Cypress version.

```json
    "@devtools-ai/cypress-sdk": "0.1.8",
    "cypress": "12.3.0"
```

To reproduce this issue, pls clone this repository (https://github.com/dev-tools-ai/devtoolsai_demo_cypress) and replace the version same as mentioned above.
